### ISSUE TITLE
Bug with city statistics on high view links

### ISSUE THREAD

**Issue by jakkuh** [shlinkio/shlink-web-client#118]
Have a weird bug / crash with a link with 50k visits and a ton of different cities.

https://i.imgur.com/A9wdXbe.png

See the side bar, it must be several thousand lines long... seems to need pagination :P
https://i.imgur.com/Nd7Xh61.png

note: it doesn't result in any errors in the console.

**Comment by acelaya** [comment]
Oh, we are probably hitting some limit here, either on the native rendering of SVGs or something in the abstraction library (which is chart.js, by the way).

I'm not really sure how to "paginate" this, but I will try to come up with something.

**Comment by acelaya** [comment]
I have implemented a client-side pagination that will allow you to just render part of the dataset.

You can see the behavior here https://www.youtube.com/watch?v=DbTt1v21rcs

This also sort of fixes #119, since the map now allows displaying only pins for the cities in the active page when pagination is enabled.

This is part of v2.0.3, which is already released, and will be published in https://app.shlink.io in the next hour/s

**Comment by acelaya** [comment]
The only thing left is that, if the amount of pages is too big, the pagination component might overlap with the chart, since it is sticky.

Let me know if that's the case, and I will try to make it render with ellipsis.
