### ISSUE TITLE
Include Title / Long URL in Statistics List View & CSV

### ISSUE THREAD

**Issue by mdrxy** [shlinkio/shlink-web-client#1273]
### Summary

<img width="1144" alt="Screenshot" src="https://github.com/user-attachments/assets/7b50bd56-3d37-4378-a15f-5af118aff0ce">

The addition of long titles could potentially be an option that is toggled on/off by the user. This should also carry over to CSV exports.

### Use case

Browsing at a glance it would be nice to see the long titles for URLs instead of having to search for the random slug or visit the link to decipher what page is being visited.

**Comment by acelaya** [comment]
The title is always the same, so I don't see the point on adding it to the table.

Something similar happens with the long URL, but since Shlink has the option to dynamically redirect to different places, this is already planned, but depends on a [missing capability](https://github.com/shlinkio/shlink/issues/2032) on Shlink.

**Comment by mdrxy** [comment]
What do you mean the title is always the same? Long titles are set at a per-short-link basis. Perhaps I am misunderstanding you?

**Comment by acelaya** [comment]
See [my comment here](https://github.com/shlinkio/shlink-web-client/issues/1275#issuecomment-2306432171).

Once the capability referenced there is implemented, we can enhance this list so that you can cross-reference visits with the short URL that produced them.
