### ISSUE TITLE
IP address redirect option not showing up

### ISSUE THREAD

**Issue by hezor** [shlinkio/shlink-web-client#1330]
### shlink-web-client version

4.2.1

### How do you use shlink-web-client

Docker image

### Current behavior

Hello!

We have a Shlink setup running in AWS Fargate with three instances that sync cache and lock data to an AWS MemoryDB (Redis cluster) and leverage the AWS RDS MariaDB as a data storage.

Our current Shlink version is the official Docker image with the tag "4.2.1-roadrunner" and our Shlink Web Client is the official Docker image with the tag "4.2.1" (also running in AWS Fargate).

![Image](https://github.com/user-attachments/assets/a9fbcbe1-7516-49d7-9be1-972ba72d1b2e)

Whenever I update the Shlink Web Client, I need to remove all local web app data from my browser (or use private/incognito mode) so the new version gets loaded from AWS Fargate - and I have done this now too and all is good regarding that.

But, whenever I'm going to edit a redirect rule via Shlink Web Client, I still don't get the IP address redirect option although my Shlink and Shlink Web Client versions are the latest ones. Only options are "Device type", "Language" and "Query param". What could be the issue?

![Image](https://github.com/user-attachments/assets/81c13405-3828-4ee7-abb3-95bfbd6a6340)

### Expected behavior

Show IP address based redirect options.

### Minimum steps to reproduce

- Run the official Shlink Docker image with the tag "4.2.1-roadrunner"
- Run the official Shlink Web Client Docker image with the tag "4.2.1"
- Configure the Web Client to use the Shlink instance
- Create a new short link
- Edit that short link with "Manage redirect rules" option
- Add a new rule
- Add a new condition
- See if the IP address option is available in the "Type" drop-down list

**Comment by acelaya** [comment]
Do you see the option here https://app.shlink.io

Do you see the option when opening your instance in an incognito window?

**Comment by acelaya** [comment]
In your web client screenshot, the close icon on the top right corner of the card is new from the same version that introduced support for ip-address redirects, so it seems the problem is that the web client thinks your server does not support that feature.

If you go to `https://your-shlink/rest/health`, what do you get back?

**Comment by acelaya** [comment]
> If you go to `https://your-shlink/rest/health`, what do you get back?

Actually, never mind. Your first screenshot just answered my question. 

The server version should be 4.2.1, without the roadrunner suffix. That's likely what is messing-up the version check to know what features are supported.

That's likely caused by a recent change in how docker tags are generated, not a problem in the web client. 

As a temporary workaround, if you use the default Shlink docker image, this should work.

**Comment by acelaya** [comment]
I created this to track the issue https://github.com/shlinkio/shlink/issues/2217

I'm closing this one as there's nothing wrong with the web client.

**Comment by hezor** [comment]
> As a temporary workaround, if you use the default Shlink docker image, this should work.

I actually tried to to use Shlink with a tag "4.2.1" (without the roadrunner suffix) but that dies on startup every time. But that is another problem then all together.

**Comment by acelaya** [comment]
I have just released Shlink 4.2.2. In that version, even when using the `-roadrunner` suffixed tag, the version reported by the server will be the right SemVer value
