### ISSUE TITLE
Allow information in active page to be automatically updated on fixed intervals

### ISSUE THREAD

**Issue by poblabs** [shlinkio/shlink-web-client#148]
Just thinking it would be nice to be able to leave the dashboard open on a screen and have it update every X seconds (300? 600?) to see it update the counters with fresh data without having to do a full page reload. 

Again, not critical and this can be declined if there's no real desire for it. 

Thanks!

**Comment by acelaya** [comment]
I like the idea. I'll add it to schedule.

**Comment by acelaya** [comment]
https://github.com/Yaffle/EventSource

**Comment by acelaya** [comment]
Hey @poblabs 

I have just finished the preliminary integration of Shlink with [mercure](https://mercure.rocks), so real-time updates will be available on Shlink from v2.2

I will now work on making shlink-web-client consume those updates, so that active pages get updated on real time (the only implemented update for now is receving visits, but that's the most important one, I guess).
