### ISSUE TITLE
Is this web client susceptible for bot attacks?

### ISSUE THREAD

**Issue by z3nth10n** [shlinkio/shlink-web-client#175]
#### Shlink web client version

* Version: 2.2.2
* How do you use shlink-web-client: self-hosted

#### Summary

I'm not sure if there is any way to protect this client against bots, but I think this is very susceptible for bot attacks.

I want to use a frontend where users registers to create short urls.

Best regards.

**Comment by acelaya** [comment]
When you say "bot attacks", are you worried that your shlink instance could get accessed by bots through shlink-web-client?

If that's the case, you don't need to worry, since all access data (like API keys and shlink URLs) gets stored in the browser's local storage.

Any bot loading it will not have access to your shlink, just to a plain static web app 🙂

You can check it by loading your shlink-web-client instance from a different browser or an incognito window. You'll see no servers are displayed.

**Comment by z3nth10n** [comment]
Yes, I reviewed the entire app, now I know that this can't be used as a shortener provider... I would need to create a registration system and a frontend where the users paste their urls (without putting the key).

**Comment by acelaya** [comment]
Yep, you will need a custom admin UI for that. This web client is not designe with that in mind.

Let me know if you come up with something. If you open source it, I will reference your app from shlink's website.
