### ISSUE TITLE
Wrong short URL affected when short code matches with and without domain

### ISSUE THREAD

**Issue by MarcHagen** [shlinkio/shlink-web-client#179]
#### Shlink web client version

* Version: 2.2.2
* How do you use shlink-web-client: app.shlink.io + Docker image

#### Summary
When creating a custom shortcode with a custom domain it is listed in the list. 
But the visit stats button doesn't work, and it cannot be edited or deleted.

#### Current behavior
Stats for `http://custom.com/linkedin` is showing stats for `http://defaultdomain.com/linkedin`
The Visit stats button redirect to `https://app.shlink.io/server/SNIP/short-code/linkedin/visits`

#### Expected behavior
Seeing the stats for the `custom.com/linkedin`

#### How to reproduce
Create a custom shortcode for the default domain.
Then create a the same shortcode for a custom domain.

**Comment by acelaya** [comment]
This probably needs a fix on Shlink side as well. I'll create the proper tickets.

Thanks for reporting.

**Comment by acelaya** [comment]
@MarcHagen I have edited the issue a bit, as this does not only affect loading visits, but also editing metadata or tags.

As I suspected, shlink is not accepting the domain in some endpoints, which makes it behave weird as soon as the short code / slug appears in more than one short URL.

https://github.com/shlinkio/shlink/issues/637 will address the issue on shlink and be released soon in v2.0.4

Then I will also fix the issue on the web client side, as it is not sending the domain anyway.

Sorry for the inconveniences. The preliminary support for multiple domains was developed in a hurry (sort of), because it was going to be a sponsored feature, which caused it to be incomplete, sadly.

**Comment by acelaya** [comment]
I'm afraid I also found a second bug which has been making short URLs using the custom domain not to have been properly tracked if there was another short URL with the same short code/slug on the default domain.

All the visits have been linked to the short URL on the default domain in those cases.

**Comment by MarcHagen** [comment]
> I'm afraid I also found a second bug which has been making short URLs using the custom domain not to have been properly tracked if there was another short URL with the same short code/slug on the default domain.
> 
> All the visits have been linked to the short URL on the default domain in those cases.

_shlinkio/shlink#644_

Yes i noticed that too, but only after some time with multi sites. Im still bit experimenting with them.

**Comment by acelaya** [comment]
v2.0.4 will bring several fixes related with multi-domain support, followed with a small fix on the web client which will make sure the domain is sent when needed.

The only problem is that I don't know if I will be able to fix all the visits that are incorrectly linked. I'll investigate.

**Comment by acelaya** [comment]
@MarcHagen I have just merged the fix for this issue, that together with the fixes released on Shlink v2.0.4 should make everything related with multiple domains work as expected.

I still need to fix one extra small bug before releasing shlink-web-client 2.3.1, but the release will happen today or tomorrow at most.
