### ISSUE TITLE
Hardreload = 404 not found

### ISSUE THREAD

**Issue by the-hotmann** [shlinkio/shlink-web-client#196]
#### Shlink web client version

* Version: v2.3.0
* How do you use shlink-web-client: self-hosted

#### Summary

I updates the Webclient to 2.3.0 (dont ask me what version it has been before).
When I go to my Server (**`https://links.domain.de/server/[CODE-CODE-CODE]/list-short-urls/1`** and HardReload it responses with a 404.

Ofc the Folder/File does not exist, but its not getting handeled right.
Also if I after this reload normal (just F5, so it gets deliovered by the Service Worker) it gets displayed again. But as soon as I hardreload its not working anymore.

Is there a way to update the ServiceWorker once after a Update to have all the new links/things?
If so, how?

(this btw does NOT happen at app.shlink.io)

**Comment by acelaya** [comment]
You need to instruct the web server you put in front of shlink-web-client to fall back to the index.html when a "non-existing file" is requested, so that the path is handled by the client-side router.

You can see here how it's done for the nginx serving the app when using the docker image https://github.com/shlinkio/shlink-web-client/issues/179

The instance served in app.shlink.io is using this docker image, that's why it does not happen there.

Thanks for bringing this to my attention. I will make sure to properly document this for other users.

**Comment by the-hotmann** [comment]
Thanks for mentioning this. I will create a PR to fix this for Apache by default if you dont mind.

**Comment by the-hotmann** [comment]
Created the PR https://github.com/shlinkio/shlink-web-client/pull/197

This is solving the Issue for Apache Setup out of the box
