### ISSUE TITLE
Display visits in a table as a log

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink-web-client#199]
#### Summary

> Moved from issue reported by @MartinH0 

Specially a more detailed "Log" below the chart would be good with the following informations:

|Date & Time|Location & IP|Browser & OS|Referer|
|:------------|:-----|:-----|:-----|
| `2020.01.31` - `01:54` | `Germany` - `Stuttgart` (`111.111.111.0`) | `Chrome (mobile)` - `Windows` | `www.hotmann.de` |
| `2020.01.31` - `01:54` | `Germany` - `Stuttgart` (`111.111.111.0`) | `Chrome (desktop)` - `MacOS` | `github.com` |
| `---` | `---` - `---` (`---`) | `---` - `---` | `---` |
| `---` | `---` - `---` (`---`) | `---` - `---` | `---` |
| `---` | `---` - `---` (`---`) | `---` - `---` | `---` |
| `---` | `---` - `---` (`---`) | `---` - `---` | `---` |

... and so on..

Cuz now we cant see anything like this in the Frontend, just in the DB itself.

**Comment by the-hotmann** [comment]
May I add that I'm somehow missing clear relations or a better visibillity of what call came from where and what referrer?

Example:
![Shlink Analytics](https://user-images.githubusercontent.com/17692860/73950602-7b8cb980-48fc-11ea-919a-f793277e00dc.PNG)
I'm missing relations between "`Referrer`", "`Country`" and "`City`"
I see 5 people are calling this Links from CloudFlare. But I cannot see recognize these calls in the "`Country`" section NOR in the "`City`" section.

The Log above (mentioned here by you) would solve this on Data-Base but not visually.

So maybe also give all Referrer from cloudFlare the Color "`orange`" and also paint them Orange (by clicking on it!) in the other fields like `Country` or `City` so they are easily to detect/recognize.

It then could look like this:
![Shlink Analytics](https://user-images.githubusercontent.com/17692860/73951360-ae837d00-48fd-11ea-872c-7429ed5ecc7f.PNG)
After "un-selecting" the referrer "CloudFlare all should look like before as otherwise it would be to colorful

The Data-Section (Log) should just show related data to the selected Link and should be sortable.


### BONUS
Hovering Data-Row should highlight the related field in all Charts

**Comment by acelaya** [comment]
It definitely sounds like something nice to have 😀

**Comment by acelaya** [comment]
Hey @MartinH0 

Let me know what you think: https://youtu.be/Mii-CymZ9r8

Things still missing

* Improve how the table renders in mobile devices
* Allowing to highlight results in the cities and countries graphs by clicking the referers one (and probably the other way around, if it's not super complex).

**Comment by the-hotmann** [comment]
Nice!!
Would be cool if IPs (anonymized) would be included :)

Are multiple selections possible? When you selected something ti is highlighted but does this also work if you select more then 1 item?

But thats exactly what I wanted :D

**Comment by acelaya** [comment]
I guess it should be possible to allow multiple selection.

As for the IP addresses, I'm afraid Shlink does not expose them, so it's not possible to display them here.

**Comment by the-hotmann** [comment]
Ofc the anonymized IPs like:
111.111.111.**0**

not the real ones like:
111.111.111.111

**Comment by acelaya** [comment]
I know, but shlink does not expose them through API or CLI tool.

**Comment by acelaya** [comment]
I'm extracting mostly everything on first comment to a separate issue, to have smaller code additions.

**Comment by acelaya** [comment]
@MartinH0 this is how it looks with support for multiple selection: https://youtu.be/6lfJJ5q5oO4

The selection in the graphs is moved to a different issue, and some improvements on the selection will be done but for a future version.

**Comment by acelaya** [comment]
And done. I have just released v2.4.0, which is also available through https://app.shlink.io

The feature is quite big, and I'm sure I missed some scenarios. Please, test it carefully and open new issues if you see any possible improvement or something does not work as expected.

**Comment by the-hotmann** [comment]
> I know, but shlink does not expose them through API or CLI tool.

Why I asked for the IP is a simple reason.
I send Links to people which life here nearby. All of them are tracked down to be here in "Stuttgart"
But tracking actually is not precise.

I life 50km from Stuttgart. 2 friends of mine life in Stuttgart direkt, some others 20-60km away.

But all are getting shown as "Stuttgart" and as most people these days use Chrome and Windows there is NO WAY to differenciate them.

But if I could see the (anonamized) IPs I could tell that these calls/visits are not comming from the same person.

So if I have 20 visits for one link they all look the same. I can not tell which call is from the same recurring person.

Maybe even setting a cookie would help to determinate a recurring visitor (if the same device is getting used) but as far as now they are not separatable. Do you understand what I mean?
If other people call the Link i want to know "its a new person" not someone who already was here.

Also: if a issue/ticket here is closed GitHub does not notify me about mentions or new comments :P

**Comment by acelaya** [comment]
I'm not really confortable exposing the IP addresses by default in Shlink. Many things could go wrong if, for example, a bug is introduced on the anonymization and the original addresses end up being exposed.

However, this is a fair point.

> But all are getting shown as "Stuttgart" and as most people these days use Chrome and Windows there is NO WAY to differenciate them.

So, let's think on some solution, but let's move the conversation to Shlink, as the changes would need to be done there first https://github.com/shlinkio/shlink/issues/725
