### ISSUE TITLE
User Agent (Platform/OS and Version) not always detected correct

### ISSUE THREAD

**Issue by the-hotmann** [shlinkio/shlink-web-client#239]
#### How Shlink is set-up

* Shlink Version: 2.1.2
* PHP Version: 7.4
* How do you serve Shlink: Self-hosted Apache
* Database engine used: MariaDB

#### Summary

"HTTP_USER_AGENT" is not used correct. I dont even know if it at all is getting used or not, but it would be a good way to determinate the OS and device of the visitor more precisely as all my calls from "Android Devices" are listed as "Linux" or "Other".
Linux in fact woulde be right but its not hard to determinate a much more informations.

For example: [LINK](https://www.php.net/manual/en/function.get-browser.php#refsect1-function.get-browser-examples)

Much more infos can be obtained.

If the output for example is: `Mozilla/5.0 (Linux; Android 8.0.0; SM-G960F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36`

The visit would come from a **Samsung Galaxy S9** running on **Android 8.0** using **Chrome v62**.

The complete output anyway should be stored in the db, if later inforamtions can be obtained better they could just be processed again.

**SM-G960F** stands for **Samsung Galaxy S9**. But using the Device-Code would be 100% fine as implementing a library with all the device codes and the clear name of the devices would be to much!

Sorry, pls change from "Bug" to "Feature Request"

---

Interesting UA parsers:

* https://www.npmjs.com/package/ua-parser-js
* https://www.npmjs.com/package/bowser

**Comment by acelaya** [comment]
Moving this issue here, as Shlink does not perform any parsing on the user agent, but just save it on its raw form.

The logic to determine OS and browser is here, and it's pretty basic (the first approach was never evolved as much as it should).

I will try to find some advanced library that does a better job parsing the user agent (there are some options).

**Comment by the-hotmann** [comment]
I would go for the "bower" package as it gets more activly developed.

**Comment by acelaya** [comment]
Yep, that would also be my first option.

**Comment by acelaya** [comment]
I have finally moved this to v2.4.0

![image](https://user-images.githubusercontent.com/2719332/79010901-32a6ea80-7b63-11ea-9e0c-78a69e548458.png)

I still had to somehow filter the list of browser, and group the "less used" in "Others", otherwise the legend was crazy big. It's more accurate anyway.

I also plan to, at some point, add some option to hide visits from bots and crawlers.
