### ISSUE TITLE
Document security caution when using servers.json

### ISSUE THREAD

**Issue by Ipstenu** [shlinkio/shlink-web-client#286]
Having `servers.json` is awesome, however the directions don't impress upon people the 'danger' of public accessibility. If you put it up on a publicly accessible URL, you allow 'anyone' who knows it's there to access. Also you have your API key in the file which means anyone who looks for the `servers.json` file can grab it if they know it's there.

1) There should be a note (or a default) in the .htaccess to block public viewing of servers.json:

```
<Files "servers.json">
  Order Allow,Deny
  Deny from all
</Files>```

2) Perhaps recommend `htpasswd` be used?

**Comment by acelaya** [comment]
This wouldn't work. It needs to be public, otherwise the web client would never be able to download it.

Serving it with http auth is also not an option, as it's loaded asynchronously.

The idea of the servers.json file is that it simplifies setting up servers in multiple machines, when you are hosting the web client yourself under a safe environment.

If the web client is publicly available you should of course never use it, and instead just rely on exporting and importing servers.

I will try to improve the docs so that the risks are clear.

**Comment by Ipstenu** [comment]
The .htaccess totally works.

I have it setup like that right now on an apache site and it's fine. It's just blocking it from being read from the browser, not the app. I do the same thing on files like wp-config.php for WordPress.

> If the web client is publicly available you should of course never use it, and instead just rely on exporting and importing servers.

Yeah that should be way more heavily documented :) People will always do the silly thing.

**Comment by acelaya** [comment]
I'm afraid it is not working as you think it is.

Shlink web client does not have a backend. The servers.json file is actually fetched through HTTP, and then processed client side.

Shlink web client runs 100% in the browser.

Once the servers.json file is processed, the list is saved in the local storage (together with anything else the app needs to be persistent) and never fetched again.

That's why it looks it's working. It was probably fetched once, then you denied the access, but the servers were already in the browser.

So it's not the same case as a wp-config.php file, which is consumed server-side, and therefore it doesn't need to be served.
