### ISSUE TITLE
Set n Days instead of date in the "enabled until..." field

### ISSUE THREAD

**Issue by Shimakuchi** [shlinkio/shlink-web-client#312]
#### Summary

To speed up the "Workflow" it would be nice if the User could also choose from default values (2 Days, 7 Days, 14 Days) for the "Enabled until" field. Could be particularly useful if the until date overlaps into the new month

![image](https://user-images.githubusercontent.com/2376419/94127772-9d21bd80-fe59-11ea-8aca-11732a383117.png)

**Comment by acelaya** [comment]
Yes, this is something I want to do.

My intention is to evolve the date component so that it supports relative dates, but also absolute ones through a date picker.

**Comment by acelaya** [comment]
I'm revisiting this, and I have realized that, for these two dates, relative times may not be as straightforward.

I have already built a new component to filter lists of short URLs or visits, which looks like this:

![image](https://user-images.githubusercontent.com/2719332/102252184-0fa8b380-3f06-11eb-8515-dd80dfc2e580.png)

I was considering something similar for this, but with just one date input. However, I have realized that "valid since" and "valid until" accept both future and past dates, so relative dates are confusing, as you have to specify if they are future dates or past dates 🤔 

* "Valid since 7 days ago"
* "Valid in 7 days"
* "Valid until 30 days ago"
* "Valid until 30 days in the future"

I'm not sure how to approach such thing.
