### ISSUE TITLE
x-api-key - use Title Case instead of lowercase

### ISSUE THREAD

**Issue by Shimakuchi** [shlinkio/shlink-web-client#322]
No that I know about the API 😜 ... 

The Screenshot says "x-api-key" but it has to be "X-Api-Key". Did not work with lowercase
![Bildschirmfoto 2020-10-05 um 10 04 08](https://user-images.githubusercontent.com/2376419/95055092-168b9c80-06f3-11eb-85d7-d311d5ffbce3.jpeg)

https://shlink.io/documentation/integrations/short-menu-mac/

**Comment by acelaya** [comment]
If that's the case, then it's a bug. Headers should not be case-sensitive.

I will investigate what could be the reason.

**Comment by Shimakuchi** [comment]
Thanks.

The API response ...
```xml
<?xml version="1.0"?>
<problem xmlns="urn:ietf:rfc:7807">
    <expectedTypes>
        <_>X-Api-Key</_>
    </expectedTypes>
    <title>Invalid authorization</title>
    <type>INVALID_AUTHORIZATION</type>
    <status>401</status>
    <detail>Expected one of the following authentication headers, ["X-Api-Key"], but none were provided</detail>
</problem>
```

**Comment by acelaya** [comment]
Ok, I think I know where the issue might be.

**Comment by acelaya** [comment]
I have just verified that it works regardless the casing, therefore, you probably didn't configre the header properly. It works with any combination of uppercase and lowercase.

The error above only happens if you don't send the header at all.

BTW, try not reporting shlink issues in shlink-web-client. This is the proper repository for those: https://github.com/shlinkio/shlink
