### ISSUE TITLE
Change theme color and other assets

### ISSUE THREAD

**Issue by mukeshwani** [shlinkio/shlink-web-client#378]
Hi there, just found this tool and installed the Shlink server and web-client on my server. I wanted to change the colors and title of the page. I found there was a manifest.json file in the build folder that had params for theme_color and background_color but changing them didn't change anything. Is there a config file that needs to be updated then a new build generated? Any help appreciated! Thanks for the tool!

**Comment by acelaya** [comment]
Hey!

I'm afraid changing the look and feel is not supported. The manifest file's purpose is to be used when installing the app as a PWA.

This topic has been considered in the past, and discarded due to the effort that would require.

However, I plan to add a dark theme to the project soon, which could open the door to support basic customizations.

I don't want to promise anything, but I'll ping you here if anything changes.

**Comment by mukeshwani** [comment]
Ok thanks for the reply!
