### ISSUE TITLE
Weird Chrome-only, macOS-only problem regarding trailing slashes in servers.json

### ISSUE THREAD

**Issue by bland328** [shlinkio/shlink-web-client#380]
#### Shlink web client version

* Version: 3.0.1 (server Docker image v2.4.0)
* How do you use shlink-web-client: Docker image

#### Summary

I've spent more hours than I care to admit trying to get shlink-web-client working, and it turns out that the whole problem was apparently lack of a trailing slash on the shlink server URL in the `servers.json` file.

#### Current behavior

Without a trailing slash on the shlink server URL in the `servers.json` file I created, shlink-web-client fails with an `Oops! Could not connect to this Shlink server` message, but **only in Chrome, and only under macOS** _(Chrome 87.0.4280.141 under macOS Catalina, FWIW)_.

I know this sounds crazy, but I've gone into Chrome DevTools and cleared all site storage _(cookies, cache and all)_, and the problem persists.

I can't find another macOS browser that has the problem, and under Windows, even Chrome works fine.

Obviously, there's a simple workaround, so I'm certainly not desperate for a fix, but wanted to drop this here in case it saves someone else an hour or three.

**Comment by acelaya** [comment]
Thanks for bringing this up.

Could you open the browser's dev console and check the network tab when trying to connect to some of these servers? Just to see if there's any API call failing.

Shlink-web-client makes a first request to the `/rest/health` endpoint in order to see if the server is reachable, and get some metadata from it.

This is probably the first malformed request and can throw some light to this.

**Comment by bland328** [comment]
Thanks for the quick response. I was just about to post again, as I'm now seeing the problem again _(but still only Chrome, and still only macOS)_, even though I have that slash in place--apparently that was a red herring.

And looks like you're correct, as in the console, I'm seeing:

```
2efd42b0-eb5d-4cef-83a9-5518fbd8c360:1 Access to XMLHttpRequest at 'https://redacted.com//rest/v2/health' from origin 'http://192.168.1.200:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Seems weird to me that Chrome is complaining about this only under macOS, but perhaps I'm just getting lucky on the other boxes from which I've tried this.

Edit: I've looked at some [shlink-related CORS documentation](https://shlink.io/documentation/api-docs/), so I should note that my shlink instance is behind an ngnix reverse proxy. Perhaps that's getting in the way...somehow?

**Comment by acelaya** [comment]
Shlink should generate de CORS headers on it's own, and if it works in other browsers, it is probably doing so.

However I see you are using plain HTTP in one of your ends. Google chrome is quite picky if the server is accessed through https when the client was served through http (or the other way around).

When this happens the error is usually different, but I have the feeling this is related.

**Comment by bland328** [comment]
The reverse proxy is publicly exposing shlink through http, but speaking to it behind the scenes via http.

shlink-web-client is not publicly exposed at all, as I'm using it solely on the LAN, and pointing it to the shlink https address via the `servers.json` file.

Do I have it straight that you're saying Chrome may be upset because my http session with shlink-web-client is creating an https session with shlink?

**Comment by acelaya** [comment]
Either that, Or the reverse proxy is removing the CORS headers https://shlink.io/documentation/troubleshooting/#response-to-preflight-request-doesn't-pass-access-control-check:-no-'access-control-allow-origin'-header-is-present

**Comment by bland328** [comment]
Using `curl -I https://redacted.com/rest/health`, I would expect to see an `Access-Control-Allow-Origin` header, but I don't.

So, I tweaked nginx to add the header with `add_header 'Access-Control-Allow-Origin' 'http://192.168.1.200:8000';` and now the problem is apparently that I'm getting too many values, which I don't understand:

```
Access to XMLHttpRequest at 'https://redacted.com/rest/v2/health' from origin 'http://192.168.1.200:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'http://192.168.1.200:8000, http://192.168.1.200:8000', but only one is allowed.
```

Plus, after the nginx tweak, `curl -I https://redacted.com/rest/health` does show the added `Access-Control-Allow-Origin` header, and only one value, as I'd expect.

I'm a little out of my depth here, but I'll report back if I work this out.

**Comment by bland328** [comment]
I now appear to have it working, except for all the changes I now need to back off or undo!

Researching this problem, I rigged nginx to always return wide-open CORS access control like this:

```
proxy_hide_header 'Access-Control-Allow-Origin';
add_header 'Access-Control-Allow-Origin' '*' always;
```

My `curl -i` results suggested that had worked, but Chrome was still unhappy.

Then, I realized Cloudflare caching might be the issue. I pulled out all the stops for nuking any cached CORS header data it might be holding on to, but that didn't help, either.

Then, with Chrome DevTools open, I long-pressed the Reload button and chose Empty Cache and Hard Reload...and everything was fixed.

I've no idea which parts of this actually helped, but I hope it helps someone else running into CORS issues.

Thanks for your help, @acelaya!

**Comment by acelaya** [comment]
@bland328 thanks for taking so much time to tackle this. It's not the usual and I so much appreciate it 🙂 

This has clearly been a combination of many things, but your findings are making me see that there could actually be a bug in Shlink, affecting a particular use case. Let me elaborate.

By default, Shlink generates the `Access-Control-Allow-Origin` header with the same value sent by the consumer in the `Origin` header. If the `Origin` header is not sent, it considers the request a server-to-server one and does not return the CORS headers at all.

On regards to the `Access-Control-Allow-Origin` header, you usually either set `*` to accept everything, or a specific set of hosts you want to trust that do not depend on anything coming from the request, as in practice, that would be equivalent as setting `*`.

However, I left it like that in Shlink as some kind of "middle ground" (you can see it here and the lines above https://github.com/shlinkio/shlink/blob/develop/module/Rest/src/Middleware/CrossDomainMiddleware.php#L35).

Now I'm thinking that, if you consume Shlink from a non-hostname environment, like opening a shlink-web-client served directly from the IP address (you were serving it in `192.168.1.200:8000`, if I remember correctly), it could cause that the browser does not consider that a valid value, and throw the same error as when the `Access-Control-Allow-Origin` header is missing.

So, the header is actually coming back, as `Access-Control-Allow-Origin: http://192.168.1.200:8000`, but the browser considers it doesn't have an acceptable value.

And also, when you were testing it from curl, since you were not sending the `Origin` header in the first place, as a browser would do, you were not getting the CORS headers back.

I will do some testing to verify all this, but probably changing Shlink to always use the value `*` for the `Access-Control-Allow-Origin` header, would solve a lot of issues that are many times hard to debug and reproduce.

**Comment by bland328** [comment]
Though I've only just now had a crash source in CORS, that all makes a lot of sense to me. Thanks for taking the time to think on it and respond--I'm more than happy to gather any data on my end that might help you out.

**Comment by bland328** [comment]
Also, for the record: I just backed off _all_ of my nginx tweaks, did the DevTools `Empty Cache and Hard Reload` again, and everything is still working. So, it is entirely possible that I had something poorly configured at some point, Chrome cached something and held on to it, and that the problem isn't with shlink-web-client at all 🤷🏻‍♂️

**Comment by bland328** [comment]
And just one more thing, @acelaya: What I'd _really_ like to do is point shlink-web to my local shlink instance and keep everything on this side of the reverse proxy, but that, unsurprisingly, fails due to CORS issues, as well:

```
Access to XMLHttpRequest at 'shlink:8080/rest/v2/health' from origin 'http://192.168.1.200:8000' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
```

Might the changes you are considering help with that case? Or would making that work be a matter of convincing shlink itself to be happy receiving requests _both_ through my `https://redacted.com` domain and it's local Docker DNS identity of `shlink`? I've no idea if such a thing is possible, but will certainly look into it.

**Comment by bland328** [comment]
Just figured out I could've saved myself a lot of hours/pain if I'd figured out sooner how to point shlink-web to my local shlink instance without going out to the internet!

My servers.json file now contains: _(note that my shlink container port 8080 is mapped to host port 8081)_

```
  {
    "name": "Local shlink connection",
    "url": "http://192.168.1.200:8081",
    "apiKey": "<redacted>"
  }
```

This is working very well.
