### ISSUE TITLE
Add UTM parameters option when creating new short url

### ISSUE THREAD

**Issue by brownsugar** [shlinkio/shlink-web-client#390]
#### Summary

Just an idea from Google's [Campaign URL Builder](https://ga-dev-tools.appspot.com/campaign-url-builder/):
![image](https://user-images.githubusercontent.com/2935980/108481591-57b3d000-72d3-11eb-9856-9a8da9080210.png)

We can just enter UTM param fields (and save the info in localstorage for next time use) without appending them to the long url manually, then create a short url.

It's a little different from **Query params forwarding**, because it don't mess up the shortened url, and it's really convenient when we need to generate lots of UTM links.

Hope to see such feature in the future, thanks!

**Comment by acelaya** [comment]
Hey!

This is already planned, but it will be implemented in Shlink to support not only hardcoded values, but also placeholders resolved at runtime.

It will also not be tied to UTM only, so that it's more flexible.

What I have in mind is to allow creating params collections that you can "link" to short URLs, so that they get appended to the long URL while redirecting the visitor.

It will also come with it's own UI in shlink-web-client.

You can subscribe to that ticket here https://github.com/shlinkio/shlink/issues/815
