### ISSUE TITLE
Do not load empty visits result sets by default.

### ISSUE THREAD

**Issue by the-hotmann** [shlinkio/shlink-web-client#407]
#### Summary

Shlink: v2.6.2 (PHP 8.0)
Shlink Web Client: v3.1.0

This happens to ALL shlink installations I ever had so the above informatiosn are just for tracking.

What I would like to prevent is the following:
When I go to the detailed view of a Short-Link the default is set to "last 30 days" which is ok for me even if I would like to default to "ALL time". But when "last 30 days" does not give back any results this "Error Info" is getting triggered:
![no visits matching current filter](https://user-images.githubusercontent.com/17692860/113507200-5bc94380-9549-11eb-9944-3a093f7f65bd.PNG)
If this happens I think the application should automaticaly fallback to "All time" instead of showing this error as the user now obviously would anyway chose "All time", but having to do this and seeing an error maybe isnt the nicest way of implementing a default time (30 days).

Therefore I think it would be cool to automatically fallback in case of "`There are no visits matching current filter :(`"

#### Feedback:
v2.6.2 (PHP 8.0) is working awesome! It even works if you run it on PHP 7.4, even if not made to do so.

##### #Shit
Just realised I posted under "shlink" instead of "shlink-web-client". Feel fre to move or delete the issue as I'm not able to move it now

**Comment by acelaya** [comment]
Yep, I think this makes a lot of sense.

Maybe a good approach would be to fetch the very last visit, and if the default date interval does not return any result, fall back to one that would, based on that visit's date.

Fetching just one visit should be quite fast, and by doing it in parallel, the impact should be mostly zero.

> I would like to default to "ALL time"

Regarding to this, shlink-web-client 3.1 has introduced the option to customize the default interval. You can change it by going to Settings.

Sadly, I did not include "All visits" as one of the options, but I honestly don't remember why. I think there was a reason, but I think it should be possible to select it if you wish.

I'll try to implement it, but in the meantime you can at least select "last 365 days" instead of "last 30 days".

**Comment by acelaya** [comment]
I have finished implementing this. It still needs some extra tests to ensure everything works as expected, but it will be part of shlink-web-client 3.5.0

I have implemented it as explained above:

* Now, the app will try to load visits for the configured default interval, and in parallel, it will load the latest visit.
* If the resulting list for that interval is empty, it will try to infer the closest interval with visits, based on the latest visit's date, and reload visits for that interval.
* If the loaded element does not have visits at all, you will still see the "There are no visits matching current filter" message, and shlink-web-client won't try to do any extra request.
* You can still manually select an interval without visits after the "first load", and in that case it will still show the message. This behavior just prevents the first load with no visits, which is certainly bad UX.

You can see the behavior here: https://youtu.be/W-ogC9uw6Bc

**Comment by acelaya** [comment]
The feature can be tested here https://shlinkio.github.io/shlink-web-client/feature/not-empty-resultsets/
