### ISSUE TITLE
Auto Connect to Server

### ISSUE THREAD

**Issue by jeremywillans** [shlinkio/shlink-web-client#490]
#### Summary

Is it possible to configure the web client to auto open the server if there is only one defined?
Right now it lands on the Welcome screen and you need to select the server manually.

**Comment by acelaya** [comment]
I'm thinking that it would even be useful to be able to determine if you want a server to be configured as the defautl one, even if you have many of them.

**Comment by acelaya** [comment]
This has been implemented and will be part of shlink-web-client 3.4

Now, you can select one of the configured servers and make shlink-web-client automatically connect to it once opened.

**Comment by benhartwich** [comment]
Is there a parameter for the servers.json file to set autoconnect here?

**Comment by acelaya** [comment]
No, I decided to enforce this to be handled from the new servers management page.

The main reason is that there should be only one server set as "auto-connect", and handling it there simplifies ensuring the state is always valid.

If the servers.json file (or the import via CSV) allowed a prop to enable auto-connect, you could potentially set it in more than one, and shlink-web-client would need to validate it somehow, opening the question of how to react:

* Throw an error?
* Enable it only on the first one which is true?
* Enable it only on the last one which is true?
* Ignore all?

Many possible outcomes and people will expect different things.

Because of that, you have to do it manually, but it's a one-time thing, so it should be ok.

I hope that clarifies it 🙂
