### ISSUE TITLE
Visits in Telemetry displays as - NaN

### ISSUE THREAD

**Issue by KLAVIATURKIN** [shlinkio/shlink-web-client#653]
#### Shlink web client version

* Version: v3.7.0
* How do you use shlink-web-client: 
server is hosted by Docker Image
Web Client used by: app.shlink.io

#### Summary

Our Visits in Telemetry once it's reaching to number more then 1_000, it's displayed as NaN, instead of Number.

#### Current behavior

number displays as NaN

#### Expected behavior

to display correct number instead of NaN

#### How to reproduce

To reach 1000 visits for Short Link(or eve Non-orphan visits)

i've attached screenshots as well for those, to see:
screenshots are taken from app.shlink.io
![By Time(less then 1000)](https://user-images.githubusercontent.com/11288889/170276813-826f24fd-981c-4f46-8cad-21f6b38f4370.png)
![By Time(more then 1000)](https://user-images.githubusercontent.com/11288889/170276816-bf0f18e5-5f07-4f9f-b315-253016142aab.png)
![By Context(more then 1000)](https://user-images.githubusercontent.com/11288889/170277707-b83a50dc-1cb1-4555-b2fa-d5cc7045b7b7.png)
![By Location(more then 1000)](https://user-images.githubusercontent.com/11288889/170276821-e49c43a8-1daa-4ec0-9a43-8d82aa5eb9bb.png)

**Comment by acelaya** [comment]
Thanks! I will check.

**Comment by acelaya** [comment]
![Captura desde 2022-05-25 18-20-42](https://user-images.githubusercontent.com/2719332/170311813-4b3066e0-7dc0-4f78-b419-d2dc6a08cd93.png)

It worksfor me. What Shlink version are you using?

**Comment by KLAVIATURKIN** [comment]
app.shlink.io tells it's latest(i see latest is 3.1.1),
but it was running on May.8, so i think it's 3.1.0

![image](https://user-images.githubusercontent.com/11288889/170318552-1b76fbfe-bf54-4687-b365-71a369732fe2.png)

**Comment by KLAVIATURKIN** [comment]
just to update:

using: `image: shlinkio/shlink:latest`
as an image, not sure probably there was some other build at May.8 as an Latest, or some test build.

cannot tell you exactly, dont have password from VM where docker is running to see

**Comment by acelaya** [comment]
So, I have a theory of what could be happening, and it's not very likely related with the version of the server.

In order to render those numbers, what this software does is bind to a hook provided by the library used to render charts.

That hook allows you to manipulate the values to be rendered, in case you want to customize them somehow.

One of the things done here is trying to make numbers more human-friendly and easier to read, by converting values like `23456` into `12,345` or `90000000` into `90,000,000`.

However, the library passes several attributes, and the one being used is called `formattedValue`. I have the suspicion that this value may be already formated, depending on the locale configured in the browser.

If the value provided is, for example, `1_000` as string, instead of `1000` as number, the casting to number will result in NaN (Not a Number).

This has never happened so far, but I think the wrong attribute might have been used here.

In what language do you have your operating system configured?

**Comment by KLAVIATURKIN** [comment]
mine PC i'm connecting from, to app.shlink.io you talking about?

if yes, it's on Russian language

**Comment by acelaya** [comment]
yes, your local PC.

Ok, I will try switching the locale.

**Comment by KLAVIATURKIN** [comment]
> yes, your local PC.
> 
> Ok, I will try switching the locale.

i just tried from Mobile Device, it's on English, but getting same as NaN
probably there is something else

![image](https://user-images.githubusercontent.com/11288889/170337594-909eea1f-38dd-4a27-acad-4d5b64b34ded.png)

**Comment by acelaya** [comment]
I have managed to reproduce it by enforcing `ru-RU` locale. In that case the formattedValue has spaces as number separator (like `12 345`).

I have changed the property to one that apparently has the value as non-formatted number, which allows me to format it with comma as number suparator (`12,345`).

**Comment by KLAVIATURKIN** [comment]
oh cool, then some other locale might coming from my Android device as well

good job man :)

**Comment by acelaya** [comment]
I have just published v3.7.1, which includes this fix.

The docker image is getting build and will be published as soon as this job finishes: https://github.com/shlinkio/shlink-web-client/runs/6598265838?check_suite_focus=true
