### ISSUE TITLE
Credentials are stripped from server URL on OPTIONS requests

### ISSUE THREAD

**Issue by rubik** [shlinkio/shlink-web-client#700]
#### Shlink web client version

* Version: 3.7.2
* How do you use shlink-web-client: Docker image

#### Summary

We are using Shlink internally and the API is protected by HTTP basic authentication. In the `servers.json` file I specified a server URL with credentials, i.e. `https://<username>:<password>@<hostname>`. When I open the app, I see that it's making requests to `https://<hostname>` without credentials, neither in the URL nor in the headers.

#### Current behavior

The web client is stripping credentials from the URLs and doesn't use them in the headers either.

#### Expected behavior

It should keep using basic authentication in some way.

#### How to reproduce

Add a server with credentials in the URL and observe that the web client is not using them when querying the API.

**Comment by acelaya** [comment]
Thanks for reporting. Let me check.

**Comment by rubik** [comment]
@acelaya Thanks for the instant reply. I found out the following:

* the URL correctly contains the credentials both in local storage and on the "Settings" page
* the request that fails is the OPTIONS request to /rest/v2/health. It's not using the credentials
* the OPTIONS request causes the GET request to /rest/v2/health to fail, even though this second request uses the credentials

**Comment by acelaya** [comment]
Hmm, that might be tricky, because the OPTIONS request is automatically performed by the browser.

Maybe if I take the credentials from the URL and make sure it is set in the `Authorization` header as basic auth, then the browser sends that header as well in the OPTIONS request.

I will do some testing and see what I can find.

**Comment by acelaya** [comment]
Just to make sure I'm not making the wrong assumption. I guess you have some kind of reverse proxy in front of your Shlink instance, which is the one handling those credentials.

Do you know how is this proxy handling those credentials?

I'm asking because I'm assuming a request to `http://user:pass@example.com` is the same as `http://example.com` with header `Authorization: Basic {base64Encode(user:password)}`, but there's a chance that's not the case depending on the service handling it.

**Comment by acelaya** [comment]
So, I have investigated, and it looks like this is the expected behavior according to the CORS specification.

If you read [this doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) and go to the `Preflight requests and credentials` section (sadly I can't link to the section directly), you will see it says the preflight request (AKA the `OPTIONS` request automatically performed by the browser before the actual request) should never require credentials.

In fact, Shlink does not validate API keys on those, as it's a pure meta-data request.

So you will need to configure your reverse proxy to not require the basic auth when the request method is OPTIONS.

**Comment by rubik** [comment]
@acelaya Thanks for the details, you are right. Indeed, we have a reverse proxy in front of Shlink's services. We'll allow the OPTIONS requests without credentials and it should solve the issue.
