### ISSUE TITLE
Add colour scheme + custom logo option

### ISSUE THREAD

**Issue by jakkuh** [shlinkio/shlink-web-client#76]
I've been changing the colour scheme in CSS with every update but it would be nice to have an option for this.

**Comment by acelaya** [comment]
I'm afraid I have to decline this.

This web client is provided as an out-of-the-box solution to be able to use shlink since the moment you download it.

Adding UI personalization options would require an important amount of development and maintenance time that I don't have right now.

I'm sorry to not being able to give you a positive answer. You have provided very valuable feedback to the project, but I think it's better to not say that I will do it in the future, because it's probably never going to be the priority.

Thanks, and sorry again.
