### ISSUE TITLE
Interoperability between CSV export and import

### ISSUE THREAD

**Issue by tostt** [shlinkio/shlink-web-client#826]
Shlink web client version
Version: 3.5.4

#### Interoperability between CSV export and import

First, congratulations for this beautiful piece of software. It's impressive to see how a simple idea can evolve into a multi faceted piece of tech.

I have a small quibble: shlink is currently unable to import CSV exports from the web-client for short URLs (not talking about the visits counts).
I think this could be solved in the exporting module by exporting two more columns : domain and short code (that info is arealdy exported combined in the shortUrl column).

Maybe renaming the columns to have consistency between export and import cloud be useful. But it can be done by hand, so it's not as much an issue.

Thank you for reading.

**Comment by acelaya** [comment]
This was supposed to be the case. I remember testing this specifically in the past, but I guess I have messed up something since.

**Comment by acelaya** [comment]
I have updated the CSV so that it includes shortUrl and Domain columns.

I have also changed the importing on Shlink so that it works with the previous format.

I figured that will make newer versions of Shlink work with older versions of shlink-web-client, but also the other way around.

The fixes will be released with next Shlink and shlink-web-client versions.
